sudo: false
language: node_js
node_js:
  - '8'
  - '10'
  - '12'

before_install:
  - travis_retry npm install

script:
  - npm test

deploy:
  provider: npm
  email: volodymyr@wildwolf.name
  api_key:
    secure: jMD7P0POegr6m948x/4Cg2c/JrPv4oddOmno7P4NClVbCQ3iAZjPveTR76Eu8vkVMDteDLaDGiscw5LFIgK5sLdpI4gOOFuheZ+U3LuMdP0kgU4SCeIQCu4zeANzpruHw1wFev2WS0i5YXU5cDOwAubTeMq3Rar5yE45+Ps6z/LC+CswY8Ai/CPCkL+tp3D6/JsLvuGJO4pIY91aJEP96bpYtLF8xEDGCM+m2HAe+72I4lwNvTwa5b3JazZ0nXEReF3+r/xswBgNFaE4IaQNVzjlTdVTLLX2zxsmHcdWHop/QNQ+VUWAE4dkc6VpQsFEJpEtCuJJ9KJ3c9rlVCfpmxOpKp+kG/y2KQgZap6HGGjXruNZC0tOnpI6CvoB7u1wkpLxzl7LcUSIlir5oGcGLLoZu1eZnev8aoljYb28PPCFl7Dl00ZBAbtChQZ3R+VtDzInkJEvZL4bv0YS7AJ4Jw979DQY3lqjPjC0piyxqM8N/dbQvUCuLHTDlG9nLTe+hegGcLF5yHuq3ucv4dx3i9uqbJp2ve1AteakoHZCSTkzUjdAZurzHvxYRpNMrqHbqzks9rNGvrf4XdSMLQO813A5YyyiATAHvMoggXslEzkqRuD9aHMcnQ3GOWXyMcra0MQXpDGDqrkafWQR5dkn0iS5IP3zGdcTQChYHzcHSyw=
  on:
    tags: true
    repo: sjinks/fastify-favicon
