name: Build and Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12', '14']

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies and test
        run: npm cit
