name: Build and Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12', '14']

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies and test
        run: npm cit
